"""initial database schema

Revision ID: 029a2dc11b69
Revises: 
Create Date: 2026-08-04 10:24:20.270509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029a2dc11b69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False, comment='Semantic model version string (e.g. v1.2.0)'),
    sa.Column('algorithm', sa.String(length=50), nullable=False, comment='Machine learning algorithm implementation (e.g. xgboost)'),
    sa.Column('training_dataset_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the dataset used for model training'),
    sa.Column('feature_schema_version', sa.String(length=32), nullable=False, comment='Version of the feature engineering schema'),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.Column('auc', sa.Float(), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False, comment='Filesystem path to model artifact file'),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when model training completed'),
    sa.Column('training_duration_seconds', sa.Float(), nullable=True, comment='Duration of model training execution in seconds'),
    sa.Column('cross_validation_score', sa.Float(), nullable=True, comment='Mean cross-validation score'),
    sa.Column('dataset_size', sa.Integer(), nullable=True, comment='Total sample count in training dataset'),
    sa.Column('random_seed', sa.Integer(), nullable=True, comment='Random seed initializer used for model reproducibility'),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=True, comment='Git commit SHA of codebase when model was trained'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('accuracy >= 0 AND accuracy <= 1', name=op.f('ck_model_versions_accuracy_range')),
    sa.CheckConstraint('auc >= 0 AND auc <= 1', name=op.f('ck_model_versions_auc_range')),
    sa.CheckConstraint('f1 >= 0 AND f1 <= 1', name=op.f('ck_model_versions_f1_range')),
    sa.CheckConstraint('precision >= 0 AND precision <= 1', name=op.f('ck_model_versions_precision_range')),
    sa.CheckConstraint('recall >= 0 AND recall <= 1', name=op.f('ck_model_versions_recall_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions'))
    )
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_repository_id', sa.Integer(), nullable=False, comment='External unique numeric GitHub repository ID'),
    sa.Column('owner', sa.String(length=100), nullable=False, comment='Repository owner organization or user handle'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Repository name'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Combined owner/name repository slug identifier'),
    sa.Column('default_branch', sa.String(length=100), nullable=False, comment='Primary Git branch name'),
    sa.Column('language', sa.String(length=50), nullable=True, comment='Primary programming language'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='Repository visibility scope (e.g. public, private)'),
    sa.Column('archived', sa.Boolean(), nullable=False, comment='Flag indicating if repository is archived'),
    sa.Column('fork', sa.Boolean(), nullable=False, comment='Flag indicating if repository is a fork'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories'))
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_github_repository_id'), 'repositories', ['github_repository_id'], unique=True)
    op.create_index(op.f('ix_repositories_owner'), 'repositories', ['owner'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False, comment='Timestamp representing when the repository state snapshot occurred'),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.Column('network_count', sa.Integer(), nullable=False),
    sa.Column('size_kb', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('topics_json', sa.JSON(), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('forks >= 0', name=op.f('ck_repository_snapshots_forks_non_negative')),
    sa.CheckConstraint('open_issues >= 0', name=op.f('ck_repository_snapshots_open_issues_non_negative')),
    sa.CheckConstraint('stars >= 0', name=op.f('ck_repository_snapshots_stars_non_negative')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_snapshots_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_snapshots'))
    )
    op.create_index('ix_repository_snapshots_repo_snapshot_time', 'repository_snapshots', ['repository_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_repository_id'), 'repository_snapshots', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_snapshot_time'), 'repository_snapshots', ['snapshot_time'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('predicted_growth', sa.Float(), nullable=False, comment='Predicted repository growth metric delta/rate'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Prediction confidence score between 0 and 1'),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when prediction was calculated'),
    sa.Column('prediction_horizon_days', sa.Integer(), nullable=False, comment='Prediction forecast horizon window in days'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_predictions_confidence_range')),
    sa.CheckConstraint('prediction_horizon_days > 0', name=op.f('ck_predictions_horizon_positive')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_predictions_model_version_id_model_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], name=op.f('fk_predictions_repository_snapshot_id_repository_snapshots'), ondelete='CASCADE'),
    sa.UniqueConstraint('repository_snapshot_id', 'model_version_id', 'prediction_horizon_days', name=op.f('uq_predictions_prediction_model_snapshot_horizon'))
    )

    op.create_index('ix_predictions_created_at', 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_repository_snapshot_id'), 'predictions', ['repository_snapshot_id'], unique=False)
    op.create_table('prediction_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False, comment='Human-readable prediction narrative summary'),
    sa.Column('top_positive_features', sa.JSON(), nullable=False, comment='Top positive feature SHAP contribution weights dictionary mapping'),
    sa.Column('top_negative_features', sa.JSON(), nullable=False, comment='Top negative feature SHAP contribution weights dictionary mapping'),
    sa.Column('shap_json', sa.JSON(), nullable=False, comment='Full SHAP feature importance dictionary mapping'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_explanations_prediction_id_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_explanations'))
    )
    op.create_index(op.f('ix_prediction_explanations_prediction_id'), 'prediction_explanations', ['prediction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_explanations_prediction_id'), table_name='prediction_explanations')
    op.drop_table('prediction_explanations')
    op.drop_index(op.f('ix_predictions_repository_snapshot_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index('ix_predictions_created_at', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_repository_snapshots_snapshot_time'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_repository_snapshots_repository_id'), table_name='repository_snapshots')
    op.drop_index('ix_repository_snapshots_repo_snapshot_time', table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    op.drop_index(op.f('ix_repositories_owner'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repository_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
